CREATE TABLE IF NOT EXISTS products (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        TEXT NOT NULL,
    handle       TEXT NOT NULL,
    body_html    TEXT NOT NULL DEFAULT '',
    vendor       TEXT NOT NULL DEFAULT '',
    product_type TEXT NOT NULL DEFAULT '',
    tags         TEXT NOT NULL DEFAULT '',
    status       TEXT NOT NULL,
    options      JSONB NOT NULL DEFAULT '[]'::jsonb,
    variants     JSONB NOT NULL DEFAULT '[]'::jsonb,
    images       JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at   TIMESTAMPTZ NOT NULL,
    updated_at   TIMESTAMPTZ NOT NULL,
    published_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_products_vendor ON products (LOWER(vendor));
CREATE INDEX IF NOT EXISTS idx_products_product_type ON products (LOWER(product_type));
CREATE INDEX IF NOT EXISTS idx_products_status ON products (status);
CREATE INDEX IF NOT EXISTS idx_products_handle ON products (handle);
